In [1]:
import numpy as np

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [23]:
##Create an array of 10 five
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [30]:
##Create an array of all the even integers from 10 to 50
array = np.arange(10,50,2)
print ("array of all the even number integers from 10 to 50")
print(array)

array of all the even number integers from 10 to 50
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


In [36]:
##Create a 3x3 matrix with values ranging from 0 to 8
np.arange(0, 9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### import numpy as np
x = np.arange(10, 50,)
print("Array from 10 to 50:")
print(x)

In [31]:
##Create a 3x3 identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
##Use NumPy to generate a random number between 0 and 1
np.random.normal(0,1)

0.09040659926142362

In [38]:
##Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution
np.random.normal(0,1,25)

array([-2.90626398,  0.41550934, -0.22749929, -0.97685217, -1.10300503,
        0.06898861,  1.69091449,  0.11539456,  0.47792729,  0.00491134,
        0.67919378, -1.13728877, -0.05767037,  0.12143341,  0.42256292,
       -0.11496488, -0.27046597,  1.52834267, -0.51525453,  0.91748404,
       -0.0634793 ,  0.50998814,  0.05666311, -0.93366855, -1.60142325])

In [42]:
##Create the following matrix
np.arange(0,1,0.01)

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99])

In [39]:
##Create an array of 20 linearly spaced points between 0 and 1
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [41]:
np.arange(10,100,3)

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58,
       61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97])

In [102]:
women = np.arange(10,200,50)
women

array([ 10,  60, 110, 160])

In [104]:
women.min()

10

In [105]:
women.argmin()

0

In [107]:
women.argmax()

3

In [108]:
np.argmin?

In [109]:
women.shape()

TypeError: 'tuple' object is not callable

In [111]:
treatment = ["olive oil", "turmeric oil", "shampoo", "relaxer"]
oil = treatment[0:2]
oil

['olive oil', 'turmeric oil']

In [113]:
cleanser = treatment[2:]
cleanser

['shampoo', 'relaxer']