In [1]:
import numpy as np

In [3]:
m = np.arange(1,25).reshape(6,4)
m

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [5]:
m[[2,3],1:3]

array([[10, 11],
       [14, 15]])

In [6]:
m[[1,2,3,4],1:]

array([[ 6,  7,  8],
       [10, 11, 12],
       [14, 15, 16],
       [18, 19, 20]])

In [10]:
m[[2,4],1::2]

array([[10, 12],
       [18, 20]])

In [11]:
m[[0,2,4],0::3]

array([[ 1,  4],
       [ 9, 12],
       [17, 20]])

In [12]:
m[[0,3],1:3]

array([[ 2,  3],
       [14, 15]])

In [14]:
m[[1,3,4], ]

array([[ 5,  6,  7,  8],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [15]:
m[[1,3,4],::3]

array([[ 5,  8],
       [13, 16],
       [17, 20]])

In [23]:
##Generate random prices between 1000 - 10000 of 200 customers
import numpy as np
np.linspace(1000,10000,200,dtype=int)

array([ 1000,  1045,  1090,  1135,  1180,  1226,  1271,  1316,  1361,
        1407,  1452,  1497,  1542,  1587,  1633,  1678,  1723,  1768,
        1814,  1859,  1904,  1949,  1994,  2040,  2085,  2130,  2175,
        2221,  2266,  2311,  2356,  2402,  2447,  2492,  2537,  2582,
        2628,  2673,  2718,  2763,  2809,  2854,  2899,  2944,  2989,
        3035,  3080,  3125,  3170,  3216,  3261,  3306,  3351,  3396,
        3442,  3487,  3532,  3577,  3623,  3668,  3713,  3758,  3804,
        3849,  3894,  3939,  3984,  4030,  4075,  4120,  4165,  4211,
        4256,  4301,  4346,  4391,  4437,  4482,  4527,  4572,  4618,
        4663,  4708,  4753,  4798,  4844,  4889,  4934,  4979,  5025,
        5070,  5115,  5160,  5206,  5251,  5296,  5341,  5386,  5432,
        5477,  5522,  5567,  5613,  5658,  5703,  5748,  5793,  5839,
        5884,  5929,  5974,  6020,  6065,  6110,  6155,  6201,  6246,
        6291,  6336,  6381,  6427,  6472,  6517,  6562,  6608,  6653,
        6698,  6743,

In [26]:
##Create three variables called expensive, fair, cheap using boolean indexing on the prices generated for customers. cheap(1000-2499), fair(2500-4999) and expensive(5000-10000)
import pandas as pd


In [ ]:
dict = {'cheap': [1000 2499], 'fair': [2500-4999], 'expensive': [5000-10000]}